<?php
$z[0]=Array("field","",254,273);
$z[0][4]['name']="title";
$z[1]=Array("global","",274,300);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",341,370);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",410,468);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",960,995);
$z[4][4]['filename']="head.htm";
$z[5]=Array("field","",1297,1318);
$z[5][4]['name']="content";
$z[6]=Array("arclist","        \r\n         <div class=\"db_01\">\r\n		     <div class=\"db_title\">[field:title/]</div>\r\n			 <div class=\"db_neirong\">\r\n			   <p>[field:body/]</p>			   \r\n			 </div>\r\n			 <div class=\"db_bottom\"><img src=\"/templets/images/td_ms_22.gif\"></div>\r\n		 </div>\r\n		 ",1479,1818);
$z[6][4]['row']="100";
$z[6][4]['typeid']="1";
$z[6][4]['addfields']="body";
$z[6][4]['channelid']="1";
$z[7]=Array("include","",2115,2152);
$z[7][4]['filename']="footer.htm";

?>