<?php
$z[0]=Array("field","",254,273);
$z[0][4]['name']="title";
$z[1]=Array("global","",274,300);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",341,370);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",410,468);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",1179,1214);
$z[4][4]['filename']="head.htm";
$z[5]=Array("arclist"," \r\n	 <li><IMG src=\"[field:litpic/]\"></li>\r\n	 ",1605,1701);
$z[5][4]['row']="100";
$z[5][4]['typeid']="51";
$z[6]=Array("arclist"," \r\n	<div class=\"dx_anli\">\r\n	    <div class=\"dx_sm\">\r\n		   <h4>[field:title/]</h4>\r\n		   <p>[field:description/]</p>\r\n		</div>\r\n		<div class=\"dx_pic\"><img src=\"[field:litpic/]\"></div>\r\n		<div id=\"clear\"></div>\r\n	</div>\r\n	<div class=\"jianxi\"><img src=\"/templets/images/chukp_09.gif\"></div>\r\n	  ",19184,19527);
$z[6][4]['row']="100";
$z[6][4]['typeid']="17";
$z[7]=Array("include","",19615,19652);
$z[7][4]['filename']="footer.htm";

?>