<?php
$z[0]=Array("field","",254,273);
$z[0][4]['name']="title";
$z[1]=Array("global","",274,300);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",341,370);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",410,468);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",1036,1071);
$z[4][4]['filename']="head.htm";
$z[5]=Array("channel","\r\n			<a href='[field:typelink /]'>[field:typename/]</a>\r\n		",1179,1287);
$z[5][4]['row']="10";
$z[5][4]['type']="son";
$z[6]=Array("type"," \r\n		<h3 class=\"title\">[field:typename/]</h3>\r\n	",1460,1543);
$z[6][4]['typeid']="32";
$z[7]=Array("arclist","\r\n		<div><a href='[field:arcurl/]'>[field:title/]</a></div>\r\n		<div class=\"gs_content\">[field:info/]</div>\r\n	",1578,1737);
$z[7][4]['typeid']="32";
$z[7][4]['row']="10";
$z[8]=Array("type"," \r\n		<h3 class=\"title\">[field:typename/]</h3>\r\n	",1804,1888);
$z[8][4]['typeid']="168";
$z[9]=Array("arclist","\r\n		<div><a href='[field:arcurl/]'>[field:title/]</a></div>\r\n		<div class=\"gs_content\">[field:info/]</div>\r\n	",1923,2083);
$z[9][4]['typeid']="168";
$z[9][4]['row']="10";
$z[10]=Array("type"," \r\n		<h3 class=\"title\">[field:typename/]</h3>\r\n	",2151,2235);
$z[10][4]['typeid']="169";
$z[11]=Array("arclist","\r\n		<div><a href='[field:arcurl/]'>[field:title/]</a></div>\r\n		<div class=\"gs_content\">[field:info/]</div>\r\n	",2261,2421);
$z[11][4]['typeid']="169";
$z[11][4]['row']="10";
$z[12]=Array("include","",2721,2758);
$z[12][4]['filename']="footer.htm";

?>